//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class barang
    {
        public int id { get; set; }
        public string nama_barang { get; set; }
        public string deskripsi { get; set; }
        public Nullable<int> jumlah { get; set; }
        public Nullable<int> harga { get; set; }
        public string gambar { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public string update_by { get; set; }
        public Nullable<int> active { get; set; }
    }
}
